<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIApKnK\AppApp_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIApKnK/AppApp_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerSIApKnK.legacy');

    return;
}

if (!\class_exists(AppApp_KernelTestContainer::class, false)) {
    \class_alias(\ContainerSIApKnK\AppApp_KernelTestContainer::class, AppApp_KernelTestContainer::class, false);
}

return new \ContainerSIApKnK\AppApp_KernelTestContainer([
    'container.build_hash' => 'SIApKnK',
    'container.build_id' => '9831681e',
    'container.build_time' => 1593100564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIApKnK');
