version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www:rw
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php
    build:
      context: .
      dockerfile: app.docker
    volumes:
      - ./code:/var/www:rw
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
