<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHH3fw30\AppApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHH3fw30/AppApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHH3fw30.legacy');

    return;
}

if (!\class_exists(AppApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHH3fw30\AppApp_KernelDevDebugContainer::class, AppApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHH3fw30\AppApp_KernelDevDebugContainer([
    'container.build_hash' => 'HH3fw30',
    'container.build_id' => '56568263',
    'container.build_time' => 1593100783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHH3fw30');
