<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_recipe_index' => [['best_before', 'use_by'], ['_controller' => 'App\\RecipeController::index'], [], [['variable', '/', '[^/]++', 'use_by', true], ['variable', '/', '[^/]++', 'best_before', true], ['text', '/api/lunch']], [], []],
];
